### ISSUE TITLE
A question about combination norse with traditional neural networks in deep learning.

### ISSUE THREAD

**Issue by hkx123** [norse/norse#102]
Does norse can combination with some mainstream traditional neural networks like ResNet？
And do you have a more detail document for use?
Thank you.

**Comment by Jegp** [comment]
Thanks for the question! :-)
All our neuron models are implemented as `torch.nn.Module`s, so they can in principle be added to any models. The one thing to know is that spiking models works over time, so just plugging it in a ResNet model (like [the PyTorch vision implementation](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py)) is likely not a good idea. You'd either have to simulate some stimulus over time (like we do in the [encode modules](https://norse.github.io/norse/auto_api/norse.torch.module.encode.html)) or at least provide some meaningful initial parameters to the neuron membrane equation (so you at least have a *chance* of some neurons firing - for instance by setting the membrane potential to non-zero, see below).

Our documentation is sparse, but having good descriptions for exactly this is actually high on our agenda. Feel free to open an issue with specific requests we can accomodate.

The current version of Norse also doesn't work well with `torch.nn.Sequential`. But we're working on that in #95 


Here's an example of setting a neuron membrane potential:

```python
import torch
from norse.torch.module.lif import LIFCell, LIFState

data = torch.ones(5, 10)
cell = LIFCell(10, 2) # 10 -> 2
batch_size = 5 
# This is a default state where the membrane potential is 0
default_state = cell.initial_state(batch_size, "cpu")
z, new_state = cell(data) # z is all zeros: no spikes!

# Let's try with a "loaded" state
loaded_state = LIFState(
    z = torch.zeros(batch_size, 10),
    v = torch.rand(batch_size, 10) + 0.5, # Random values with mean 0.5 and stddev 1
    i = torch.zeros(batch_size, 10)
)
z, new_state = cell(data) # z now contains spikes because we set the membrane potential v to > 0
```

**Comment by cpehle** [comment]
To add an additional point to the discussion: There is two possible ways of combining traditional CNNs with the spiking models in Norse.

1. You can implement part of the network with a preexisting image recognition model and connect that at each timestep to a spiking neural network model. We don't have an example for such a use case yet, but I will probably get around to implement something like that in the near future. One thing to take into account is that most of the spiking neuron models expect spikes (valued 0,1).
2. You can implement a Resnet architecture directly with Spiking neurons as was done for example in ["Going Deeper in Spiking Neural Networks: VGG and Residual Architectures", Sengupta et al.](https://www.frontiersin.org/articles/10.3389/fnins.2019.00095/full). We want to support that use case aswell (#32 tracks the required regularisation).

We welcome any contributions in that direction, also feel free to join as on discord to discuss further: https://discord.gg/9wccdv9.

**Comment by Jegp** [comment]
It seems like the issue was resolved, so I'll close it for now. Feel free to reopen or open a new one if there is anything else we can assist with!
