### ISSUE TITLE
Example of Pytorch Lightning training

### ISSUE THREAD

**Issue by cpehle** [norse/norse#116]
Context: Pytorch lightning is an excellent tool, which makes it really easy to parallelise Pytorch models on clusters.

We should provide some example of how Norse is straightforwardly compatible with Pytorch lightning, since this sets it apart from other Pytorch based spiking neural network simulators.

**Comment by Jegp** [comment]
Agreed. We could couple this with #88 where we can provide some really nice examples (and justifications) for specific models.
