### ISSUE TITLE
Consistent *Cell, *Layer, *FeedForward shape interface

### ISSUE THREAD

**Issue by Jegp** [norse/norse#121]
We currently have a number of different ways to describe the input parameters to cells, layers, and feedforward modules. For new users this is slighthly annoying. Especially after we removed the required state parameters.

Here are three models we *could* use:
1. Flat parameters like, for instance, `(in_features: int, out_features: int, ...)`
    * Call: `LIFCell(8, 4)`
2. Single tuple: `(shape, ...)`
    * Call: `LIFCell((8, 4))`
3. Infer from neuron parameters and state
    * Call: `LIFCell()`

I personally prefer 1 because PyTorch uses this annotation and because it's straight-forward and simple to document. Any preferences?

**Comment by cpehle** [comment]
Yeah I think 1 is preferable, while we are at it we should also make sure the *FeedForward cells have a consistent API.

**Comment by Jegp** [comment]
Another related question is how we should deal with the layer models. In principle they all do the same: instantiate some state and run through the timesteps. What do you think about merging all the different `*Layer` models into one? It could look a bit like this:

```python
class NeuronLayer(...):
    def __init__(self, neuron, parameters):
        self.neuron = neuron(parameters)
    def forward(x, state=None):
        for ts in range(x):
            z, self.state = self.neuron(x[ts], state)
        return z, self.state
```

It can then be applied with different cell types like so:
```python
NeuronLayer(LIFCell)
NeuronLayer(LSNNCell)
# etc
```
