### ISSUE TITLE
population encoder

### ISSUE THREAD

**Issue by yjzhang97** [norse/norse#151]
**norse.torch.functional.encode.population_encode** 
This function should be return "A tensor with an extra dimension of size `seq_length` containing spikes (1) or no spikes (0)."
however, it return a tensor representing the spike time rather than a 0/1 sequence.
Thank you!

**Comment by Jegp** [comment]
Thanks for submitting the issue! Actually, the documentation is wrong; the population encode encodes the stimulus to numerical rates. One way to achieve spikes directly is to couple it with a Poisson generator that interprets the numerical values as spikes, like so:

```python
import norse 
norse.torch.poisson_encode(norse.torch.population_encode(torch.ones(10, 10), 10), 1).squeeze()
```

That should give you the same dimensionality. I've updated the documentation.

**Comment by yjzhang97** [comment]
Thanks for your reply. 
Actually, I want to use temporal population encoder as shown below. 
![image](https://user-images.githubusercontent.com/43169876/98541602-a7453180-22ca-11eb-93c5-3913c2404a8c.png)
I have successfully built this encoder based on norse.

**Comment by Jegp** [comment]
Excellent! If you don't mind sharing your code, we'll be happy to include that change :-)

I'll close the issue for now, but feel free to re-open or start another issue if you run into any problems.
