### ISSUE TITLE
Add more meaningful example in Readme

### ISSUE THREAD

**Issue by cpehle** [norse/norse#160]
I think we should probably try to showcase the library in a more meaningful way than the LSNN example we currently have.

**Comment by Jegp** [comment]
Indeed. I would like to showcase something where we demonstrate a high-level use of Norse. Like import data, build network, train network with <= 10 lines of code. Unfortunately we're not quite there yet with the Module API I'm afraid. It'd be great if we can standardise the Layer idea so we have a cleaner interface for that.

Or do you have a specific idea in mind?

**Comment by Jegp** [comment]
I think we can close this issue with the latest push. But we should continue to improve our documentation/examples as we reveal improvements and cooler models
