### ISSUE TITLE
Broken link to SpikingJelly's tutorial

### ISSUE THREAD

**Issue by Yanqi-Chen** [norse/norse#165]
Sorry for disturbing you again, but the link to SpikingJelly's tutorial still lacks a character 'l' at the end.
Now:
https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven_en/3_fc_mnist.htm
Should be:
https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven_en/3_fc_mnist.html

**Comment by cpehle** [comment]
Ah copy and paste error, it works now.

**Comment by Yanqi-Chen** [comment]
Thanks!
