### ISSUE TITLE
C++ modules are not loaded correctly on macOS

### ISSUE THREAD

**Issue by cpehle** [norse/norse#184]
This code fails on macOS

```python
try:
    import torch
    from pathlib import Path

    print(Path(__file__).resolve().parent.parent)

    torch.ops.load_library(Path(__file__).resolve().parent.parent /  "norse_op.so"
    import sys

    setattr(sys.modules[__name__], "IS_OPS_LOADED", True)
except OSError:
    import sys

    setattr(sys.modules[__name__], "IS_OPS_LOADED", False)
```

**Comment by cpehle** [comment]
Short term solution is to temporarily disable this optimisation and reintroduce it once the more comprehensive C++ primitives land.

**Comment by Jegp** [comment]
As far as I understand it's only a problem in the test, right? Meaning, the actual code is unaffected. Can't we just survive the fact that they'll fail on mac until we get a chance to fix the bug?

**Comment by cpehle** [comment]
> As far as I understand it's only a problem in the test, right? Meaning, the actual code is unaffected. 

Not entirely sure actually, in any case loading library like this is the wrong thing to do (TM). Because on windows/Mac the dynamic library postfixes are different. Separately the path the library is loaded from is also kind of wonky, not sure what to do about that.
