### ISSUE TITLE
TPU Support

### ISSUE THREAD

**Issue by cpehle** [norse/norse#186]
This issue tracks changes needed to support TPUs. First observation is that some operations
are not supported by the XLA Jit, so they need to be eliminated (torch.gt is one example).
Second would to make sure that loops are translated to appropriate calls to XLA.scan.

**Comment by Jegp** [comment]
Nice issue. Do you have a list of supported operations somewhere?

**Comment by cpehle** [comment]
> Nice issue. Do you have a list of supported operations somewhere?

Here is a guide: https://pytorch.org/xla/release/1.7/index.html#op-lowering-guide. We can probably follow that.

**Comment by Jegp** [comment]
@PMMon recently showed that the notebooks run with TPUs. We could, of course, test for all methods. But since the use case may be limited now, I would suggest closing this for now.
Comments @cpehle ?

**Comment by cpehle** [comment]
I think we can close this provided the process of running the notebooks on TPUs is documented somewhere. Separately we should investigate what kind of performance bottlenecks exist.

**Comment by Jegp** [comment]
I added a comment on how to change the runtime in the notebooks: https://github.com/norse/notebooks/commit/6f1ea2660f9b5e3081933bf9fb1d972805188ceb
