### ISSUE TITLE
Remove autapses from recurrent modules

### ISSUE THREAD

**Issue by cpehle** [norse/norse#19]
Currently the recurrently connected spiking neural network modules allow autapses (self connections). This might not be a sensible default.

**Comment by Jegp** [comment]
Is this still something you would like? And if so, should we perhaps consider parameterizing it, so we can choose when to have autopses?

**Comment by cpehle** [comment]
Yes I think this is pretty important also for comparability with other simulators, which typically don't allow for autapses (at least optionally).
