### ISSUE TITLE
Explanation of lsnn_step and lif_step

### ISSUE THREAD

**Issue by JunwenBai** [norse/norse#190]
I think for LIFRecurrentCell and LSNNRecurrentCell, the lsnn_step() and lif_step() activation functions are important. But is there any explanation or insight of the implementation?

**Comment by Jegp** [comment]
Hi @JunwenBai. Thanks for your question. It's a good one, so I actually took the liberty to improve our documentation on the matter: #191 

The PR mostly covers leaky integrators, LIF, and LSNN dynamics, so it should give you a hint to the difference between `lsnn_step` and `lif_step`: the `lsnn` uses the adaptation term from the LSNN model, where the `lif` is "just" a simple leaky integrate-and-fire model.

However, one thing that I haven't gotten around to cover is the difference between the `feedforward_step` and just `step` functions. The difference is the same as the difference between the `LIFCell` and the `LIFRecurrentCell`. The LIFCell uses the `lif_feedforward_step` function which is simply a feedforward activation of the LIF equations. The `LIFRecurrentCell` uses the `lif_step` which is actually a recurrent version that adds input *and* recurrent weights. I admit the naming is a little confusing. 

I added some more description and code in the [quickstart documentation page](https://github.com/norse/norse/blob/feature-lsnn-doc/docs/source/started.rst).

Did that answer your question?

**Comment by JunwenBai** [comment]
Thanks! This is helpful!

**Comment by JunwenBai** [comment]
Maybe one more question: in LSNN paper, in section 2 of Supplements, the update of the adaptive threshold b_j(t) seems to involve an exponential coefficient \rho_j. However, in your lsnn_step function, the update of b_new seems to be quite different. Do you mind further explaining this?

**Comment by Jegp** [comment]
Nicely spotted and you are very right. We don't have an exponential coefficient like they do in the paper. However, the adaptation mechanism is still there, and retains a lot of the same functionality.

We are currently working on more interesting integration schemes that make it easier to code these models up. Just hard-coding everything in Euler doesn't really scale well. If you have any input or would like to add a version with an exponential coefficient, you are most welcome! :-) I'm also happy to provide tips on how to approach this. Basically, one could just copy the dynamics from the appendix you referenced.

**Comment by JunwenBai** [comment]
Cool! I did try some applications and norse seems to work fine. I'll try to see what I can do there for the exponential coefficient.
But I'm still curious, when you design the current adaptation mechanism, what was your insight? In practice, the current adaptation does work and is much simpler. I wonder whether most reasonable adaptation schemes would perform roughly the same?

**Comment by Jegp** [comment]
I think I'll defer your question about insight to @cpehle, since he actually implemented the LSNN model :-) He can be pretty hard to get in touch with, so I recommend also trying Discord.

But talking about adaptation schemes, this is likely dependent on your problem. As far as I'm aware, it is an open research question in most domains. Perhaps that could be a question to you @JunwenBai and @cpehle; are you familiar with any work on adaptation schemes in general? Perhaps related to information theory?

For completeness, issue #40 is addressing parts of this adaptation question.

**Comment by cpehle** [comment]
So this divides into two parts: 1. The numerical integration method that is chosen. 2. the synapse model that is used.

1. At the moment Norse only implements naive forward Euler integration, which is sufficient for simple point Neuron models and experiments where you have externally imposed quality criteria such as loss functions for a given task. The formulas given in the Appendix of Bellec et al. can be derived by instead using [exponential Euler integration](https://en.wikipedia.org/wiki/Numerical_methods_for_ordinary_differential_equations#First-order_exponential_integrator_method), which is another common but slightly computationally more expensive way of numerical integration. 

2. At the moment we use exponential decaying synaptic input currents, which is a common way of approximating synaptic input currents (e.g. https://www.jneurosci.org/content/jneuro/17/20/7606.full.pdf). Bellec et al. instead use "rectangular" / delta synaptic inputs, which is computationally less expensive.

I think there is no review of the utility of different adaptation mechanisms for computational tasks yet. The group of Wolfgang Maass has done a lot of pioneering work in that direction, especially in the context of larger machine learning inspired tasks. Various adaptation mechanisms in the context of computational neuroscience have of course been studied for a long time, a GitHub issue is probably not the right place to review those though :). I would be happy to continue the discussion in another medium such as our discord channel or via email and thank you for trying out Norse.

**Comment by Jegp** [comment]
Did that answer your question @JunwenBai? If so, I'd like to close the issue.

**Comment by JunwenBai** [comment]
Yes. Thx!
