### ISSUE TITLE
ImportError: cannot import name 'LICell' from 'norse.torch'

### ISSUE THREAD

**Issue by mhr** [norse/norse#198]
![image](https://user-images.githubusercontent.com/1429247/114249808-a7c12180-9969-11eb-91ac-803e4a693a4f.png)

I'm using Windows 10.

For context, the only way I was able to get Norse installed was via conda. pip gave me the following error:

```
ERROR: Failed building wheel for norse
Failed to build norse
ERROR: Could not build wheels for norse which use PEP 517 and cannot be installed directly
```

I mention this because https://anaconda.org/norse/norse shows that the conda version was last updated nearly two months ago, so that could be part of the problem.

When I try `from norse.torch import *`, I get

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-678a64761d1a> in <module>
----> 1 from norse.torch import *

~\miniconda3\envs\neuroarcade-venv\lib\importlib\_bootstrap.py in _handle_fromlist(module, fromlist, import_, recursive)

~\miniconda3\envs\neuroarcade-venv\lib\importlib\_bootstrap.py in _handle_fromlist(module, fromlist, import_, recursive)

TypeError: Item in norse.torch.__all__ must be str, not module
```

When I look at `norse.torch.__init__.py`, I get 

```
"""Norse is a library for doing deep learning with spiking neural networks.

This package contains modules that extends PyTorch with spiking neural
network functionality.
"""

from . import functional
from . import module

__all__ = [functional, module]

```

Which is not what is currently in that file in the GitHub repo: https://github.com/norse/norse/blob/master/norse/torch/__init__.py.

Anyway, in order to import LICell, I found the only way with the conda package is `from norse.torch.module.leaky_integrator import LICell`.

I tried installing from the source, but that also gave me issues.

**Comment by cpehle** [comment]
Thanks for bringing this to our attention. There was another recent issue raised regarding Windows 10 support. I will investigate both tomorrow.

**Comment by Jegp** [comment]
Wow, thanks for your persistence here! I think you've actually run into several issues, probably all related to windows: Conda install, pip install, and source install.

It looks like you've installed version 0.0.3 from Conda. Which is indeed strange. I will try to find a Windows machine and try to replicate the problems with source, pip, and Conda.

And as @cpehle said: thanks for bringing this to our attention!

**Comment by Jegp** [comment]
I can confirm that the Conda installation fails on a clean Windows 10 installation. Even with all the prerequisites installed. This is odd because I spent quite a bit of time building conda versions specifically for Windows. I'll look into this further today.

However, both the pip and source installation fails as well. I installed the necessary C++ VSCode libraries, but there are still some compilation problems with Torch. It seems like others are having similar problems when building PyTorch extensions. Perhaps you have some insights here @cpehle?

**Comment by Jegp** [comment]
For posterity: conda is failing on Windows without proper errors. We are waiting for issues in the Conda repo (https://github.com/conda/conda/issues/10324 and https://github.com/conda/conda/issues/10443). But with >2k open issues, it seems unlikely to be fixed anytime soon. For now, we recommend using Docker.

**Comment by luxmikant** [comment]
i am getting the same error on kaggle notebook import error of torch.functional what should I do
