### ISSUE TITLE
Amend README to add instructions on how to use the Docker installation and access a Jupyter notebook from the container's host

### ISSUE THREAD

**Issue by mhr** [norse/norse#202]
As @Jegp suggested on Discord:
```
docker run --rm -it -p 8888:8888 quay.io/norse/norse bash
pip3 install jupyter
jupyter notebook --ip 0.0.0.0 --allow-root
```
to keep the container from exiting.

**Comment by Jegp** [comment]
I've added some lines in our installation guide and demoted the conda installation on the main README.

Feel free to re-open if there's something missing/broken.
