### ISSUE TITLE
Wrong comment in example (notebook) parameter learning

### ISSUE THREAD

**Issue by skiwan** [norse/norse#211]
**Describe the bug**
The example https://colab.research.google.com/github/norse/notebooks/blob/master/parameter-learning.ipynb

has a wrong description of what the odd firing model training actually does.
The comment states it trains the network so it fires every fifth time step. In reality we are training the network so that every fifth neuron of the network spikes every time step

**Comment by Jegp** [comment]
Thanks for pointing it out!

It should be fixed with b75eaab850983d1d16ec6009bf9e4334f32181dd

You are welcome to reopen if needed
