### ISSUE TITLE
Got 3 expected 2 parameters when using sequential state apply with state as parameter given

### ISSUE THREAD

**Issue by skiwan** [norse/norse#212]
When using the sequential state in the model and forward function is defined as

def forward(self, x ,state):
  self.model.apply(x, state) #where x is the data and state a state

Following error is thrown
'TypeError: apply() takes 2 positional arguments but 3 were given'

if instead the forward is defined as
def forward(self, x, state):
  self.model.forward(x, state)

everything works as expected.

**Comment by Jegp** [comment]
Closed as none-bug; `Module.apply` takes a function and applies it recursively to submodule. The behaviour we're looking for is indeed `Module.forward`.

https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module
