### ISSUE TITLE
Use of Norse in speech recognition with spectrograms.

### ISSUE THREAD

**Issue by DenisMihailapov** [norse/norse#225]
Hi, Norse's Team.
In this spring I was working on my senior project in **Novosibirsk State University**, Russia. 
This work is devoted to the application of **Norse in speech recognition using spectrograms**.
It seemed to me that little attention was paid to this topic. I hope this will help in the development of the project.
**Link on repository:** https://github.com/DenisMihailapov/Norse-ASR.

Note: The work is done in Russian, the text of the article is not yet available, but the source code can already be used.

**Comment by cpehle** [comment]
Hi, this is great! We actually have an application to the speech commands dataset in an upcoming paper on
Norse, but your work appears to be more comprehensive, so this is very nice!

**Comment by DenisMihailapov** [comment]
I saw application to the speach commands, but I has some problems to use this. Perhaps I have little experience in working with PyTorch. In general, this work is done quite clearly, even for the entry level.

**Comment by cpehle** [comment]
We actually also had problems with it :). So it is really good, that you invested the effort to work on this.

**Comment by DenisMihailapov** [comment]
Thank you!
