### ISSUE TITLE
Force all voltage tensors to be floats

### ISSUE THREAD

**Issue by Jegp** [norse/norse#228]
In https://github.com/norse/notebooks/issues/13 the voltages (copied from the input tensor) is of type `Long` and not `Float`, which crashes gradient calculations.

From my perspective, it makes most sense to retain event-based input tensors as numbers (`Int` or `Long`) and then ensure that the voltage is a floating point. Specifically, that would mean that we cast voltage and current tensors to floating points in, for instance, https://github.com/norse/norse/blob/master/norse/torch/functional/lif.py#L400

Curious to hear your input @biphasic

**Comment by biphasic** [comment]
Very nice, thanks for this
