### ISSUE TITLE
Spike-time decoding

### ISSUE THREAD

**Issue by Jegp** [norse/norse#250]
Add a function and module that permits spike-time decoding, as suggested by @schmitts https://twitter.com/sbstnschmtthd/status/1432343373072019461

**Comment by schmitts** [comment]
Thanks. I'll be happy to test anything.

**Comment by Jegp** [comment]
You're more than welcome to test out the implementation and provide feedback. I'm open to suggestions on how this can be improved/built upon.

**Comment by cpehle** [comment]
This is addressed by #321 , @schmitts 🎉, so feel free to give it a try 🙂.
