### ISSUE TITLE
Factor out examples and Jupyter notebooks into separate repository

### ISSUE THREAD

**Issue by cpehle** [norse/norse#26]
Right now we include the tutorial notebooks in the main repository. It might be better to factor them out into a tutorial repository.

**Comment by Jegp** [comment]
Agreed. We also have an awkwardly places examples directory in the root. Creating a separate directory where we can version it along the other norse versions would probably be a good idea...

**Comment by Jegp** [comment]
We could also consider keeping everything in one repositories. Examples ~= notebooks. At least I plan to use notebooks to implement new tasks/benchmarks.
