### ISSUE TITLE
Issue on page /pages/working.html

### ISSUE THREAD

**Issue by XiYuan68** [norse/norse#262]
In [https://norse.github.io/norse/pages/working.html#deciding-on-neuron-models](https://norse.github.io/norse/pages/working.html#deciding-on-neuron-models), the link of: 

[https://norse.github.io/norse/generated/norse.torch.html#neuron-models](https://norse.github.io/norse/generated/norse.torch.html#neuron-models)

doesn't point to any related infomation, the most relevant page I found is:

[https://norse.github.io/norse/norse.torch.html#neuron-models](https://norse.github.io/norse/norse.torch.html#neuron-models)

is it mislinked?

**Comment by Jegp** [comment]
Thanks for pointing this out! It is indeed mislinked, and is supposed to redirect here: https://norse.github.io/norse/norse.torch.html#neuron-models

I'll fix it momentarily.
