### ISSUE TITLE
Differentiable encoder for adversarial attacks?

### ISSUE THREAD

**Issue by XiYuan68** [norse/norse#264]
**Is your feature request related to a problem? Please describe.**
I am trying to apply adversarial attacks on SNN with PGD of foolbox. This attack requires gradients in the model. But error raised:

```
  File "/home/chenxiyuan/projects/PROJECTS/traintest.py", line 206, in attack_snn
    _, x_adv, success = attack(fmodel, x, y, epsilons=epsilon)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/foolbox/attacks/base.py", line 279, in __call__
    xp = self.run(model, x, criterion, epsilon=epsilon, **kwargs)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/foolbox/attacks/gradient_descent_base.py", line 92, in run
    _, gradients = self.value_and_grad(loss_fn, x)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/foolbox/attacks/gradient_descent_base.py", line 52, in value_and_grad
    return ep.value_and_grad(loss_fn, x)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/eagerpy/framework.py", line 352, in value_and_grad
    return t.value_and_grad(f, *args, **kwargs)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/eagerpy/tensor/tensor.py", line 543, in value_and_grad
    return self._value_and_grad_fn(f, has_aux=False)(self, *args, **kwargs)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/eagerpy/tensor/pytorch.py", line 498, in value_and_grad
    assert x.raw.grad is not None

AssertionError
```

**Describe the solution you'd like**
Supporting x.raw.grad of eagerpy to enable eagerpy-based white-box adversarial attack

**Describe alternatives you've considered**
no

**Additional context**
Here is the homepage of [foolbox](https://github.com/bethgelab/foolbox/)

**Comment by XiYuan68** [comment]
And I tried another adversarial attack toolbox [cleverhans](https://github.com/cleverhans-lab/cleverhans) which relies on native pytorch to compute the gradient instead of eagerpy, it seems that the gradient in the model is returned as None:

```
  File "/home/chenxiyuan/projects/PROJECT/attacksnn.py", line 37, in <module>
    x_adv = attack_fgsm(model, loader, 0.3)

  File "/home/chenxiyuan/projects/PROJECT/attacksnn.py", line 25, in attack_fgsm
    x_adv.append(fgm(model, x, epsilon, np.inf))

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/cleverhans/torch/attacks/fast_gradient_method.py", line 88, in fast_gradient_method
    optimal_perturbation = optimize_linear(x.grad, eps, norm)

  File "/home/chenxiyuan/.local/lib/python3.9/site-packages/cleverhans/torch/utils.py", line 81, in optimize_linear
    red_ind = list(range(1, len(grad.size())))

AttributeError: 'NoneType' object has no attribute 'size'
```

Is it possible for the model to return the surrogate gradients for these toolboxes to craft adversarial samples?

**Comment by cpehle** [comment]
I think this might be related to how you encode values into spikes. The examples in the mnist tutorial for example don't use encoders which propagate gradients, since normally you don't require gradients for the input. To generate adversarial examples this is necessary though, so you have to encode your image / whatever you are targeting in a differentiable way into spikes. There are multiple ways of doing so, I've added a documentation label for that reason. Hope that helps and maybe that is already enough for you to figure it out on your own.

**Comment by XiYuan68** [comment]
Thanks for the help! Yes I followed the mnist tutorial and the model looks like this:

```
import torch
import torch.nn as nn
from norse.torch import PoissonEncoder, LIFParameters
from norse.torch.module.lif import LIFCell


class MNISTSNN(nn.Module):
    def __init__(self, seq_length=20, decode=True):
        '''
        Refers to https://colab.research.google.com/github/norse/notebooks/blob/master/mnist_classifiers.ipynb
        
        bug: model not converging when seq_length=10
        '''
        super(MNISTSNN, self).__init__()

        self.seq_length = seq_length
        self.decode = decode

        method = "super"
        alpha = 80
        self.encoder = PoissonEncoder(seq_length)
        self.conv1 = nn.Sequential(nn.Conv2d(1, 16, 3, 1))
        self.lif1 = LIFCell(p=LIFParameters(method=method, alpha=alpha))
        self.maxpool1 = nn.MaxPool2d(2)
        self.conv2 = nn.Sequential(nn.Conv2d(16, 32, 3, 1))
        self.lif2 = LIFCell(p=LIFParameters(method=method, alpha=alpha))
        self.maxpool2 = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(32 * 5 * 5, 10)    
        self.lif3 = LIFCell(p=LIFParameters(method=method, alpha=alpha))

        
    def forward(self, x):
        
        x = self.encoder(x)
        
        batch_size = x.shape[1]
        
        # specify the initial states
        s1 = s2 = s3 = None

        spike_train = torch.zeros([batch_size, self.seq_length, 10], device=x.device)

        for ts in range(self.seq_length):
            z = self.conv1(x[ts, :])
            z, s1 = self.lif1(z, s1)
            z = self.maxpool1(z)

            # Why times 10?
            z = 10 * self.conv2(z)
            z, s2 = self.lif2(z, s2)
            z = self.maxpool2(z)

            z = z.view(z.size(0), -1)
            z = self.fc1(z)
            z, s3 = self.lif3(z, s3)

            spike_train[:, ts] = z
        
        if self.decode:
            classification = torch.sum(spike_train, dim=1)
            return classification
        else:
            return spike_train
```

I took a look into the `PoissonEncoder`, which uses `torch.rand()` to generate spikes. I'll try to set `requires_grad=True` for `torch.rand()` to see if it works. Again many thanks for the encoder explanation!

**Comment by XiYuan68** [comment]
Hi @cpehle , I come up with a differentiable Poisson encoder like this:

```
class DifferentiablePoissonEncoder(torch.nn.Module):
    def __init__(self, seq_length: int, f_max: float = 100, dt: float = 0.001):
        super(DifferentiablePoissonEncoder, self).__init__()
        self.seq_length = seq_length
        self.f_max = f_max
        self.dt = dt
        self.hardsigmoid = torch.nn.Hardsigmoid()
    def forward(self, x):
        rand = torch.rand(self.seq_length, *x.shape, device=x.device)
        x = self.dt * self.f_max * x
        spike = self.hardsigmoid((x-rand) * 100000)
        return spike
```

I trained a model with `norse.torch.PoissonEncoder`, and replace the encoder with `DifferentiablePoissonEncoder`, prediction accuracy of clean MNIST images are similar between two encoders (~0.96). And `foolbox.attacks.PGD` successfully attacks the new model (however the accuracy is unexpectedly high: 0.81 with `epsilon=0.3`). What do you think of this hardsigmoid Poisson encoder? Is it a legit replacement of `norse.torch.PoissonEncoder`?

**Comment by XiYuan68** [comment]
A little bit update for those who wants to attack SNN,  transfer attacking an ANN-converted SNN with adversarial examples crafted from the origin ANN produces similar accuracy loss in both models. Directly attacking trained-from-scratch SNN (like ones trained with `norse`) results in poor accuracy loss in both white- (PGD) and black-box (Square) attacks.
