### ISSUE TITLE
Smoothing spike activity (filter)

### ISSUE THREAD

**Issue by Pugavkomm** [norse/norse#272]
**For some tasks, it would be useful to be able to smooth out the spike output**
It is obvious that spiking neurons work over time. And I would really like to be able to use, for example, an exponential filter of the network output.

**Solution you'd like**
It might be worth adding such a layer. 

**y**(n + 1) = exp(kappa) **y**(n) + **W**out **z**(n+1), 
or
**y**(n + 1) = smth_paramaeter * **y**(n) + **W**out **z**(n+1).

kappa < 0, z -- spike variable, which is specified via the Heaviside function, n -- iteration (discrete time) 

**Argumentation**
For example, in the [e-prop](https://www.nature.com/articles/s41467-020-17236-y)  method, such an output is used (although it can be any other). 
Obviously, such a layer will make it easy to expand the possibilities of using spiking neural networks in norse.

**Comment by cpehle** [comment]
I think that is a good Idea, we currently support it in a limited way through the ```LICell```, we could additionally support an exponential filter, although it is relatively easy to implement this yourself.

**Comment by Pugavkomm** [comment]
The implementation is of course simple, but I think it would be useful for spike neural networks to have such a layer. This layer will speed up the creation of models.

**Comment by cpehle** [comment]
Yes I agree and I didn't mean to suggest that it shouldn't be included.

**Comment by Jegp** [comment]
Thanks for the input @Pugavkomm! As @cpehle mentioned, it would be a welcome addition. Do you have time to contribute this with a pull request? Don't hesitate to ask questions on our discord or reach out if you have any questions.

**Comment by Pugavkomm** [comment]
I think what can be done. In addition, I previously implemented this for myself.
