### ISSUE TITLE
Installing problem in linux server

### ISSUE THREAD

**Issue by codefwer** [norse/norse#284]
**A problem about Installing the norse**
when i used conda to install norse(v.0.0.7) in a linux server(ubuntu16.04),which can successfully be installed,but when i import norse in python,it said: _ModuleNotFoundError:No module named 'norse'_  .Then i choose to use  command ’pip install norse==0.0.7',then an error was showed: _ERROR: Could not build wheels for norse which use PEP 517 and cannot be installed directly_

**Methods been tried**
1. `conda install -c norse norse==0.0.7`  this command can successfully install norse, but can't import module.
2. `pip install norse `    this command will erupt many red mistakes,i have already uninstalled norse before using this command
3. i guessed that maybe there were some packages conflicts,so i try to create a new virtual environment using `conda create  -n  pytorch_snn  python=3.9`,then install all dependencies required , but it still didn't work

**Screenshots**
![错误2](https://user-images.githubusercontent.com/79414489/147450167-6f053de5-f7ee-4a1b-85ce-72cd4051008b.png)
![错误](https://user-images.githubusercontent.com/79414489/147450141-2b86b8a6-fb6b-4738-8563-715b1b53cfec.png)

### i had asked for help on the internet,but nobody could solve this problem.It is really a frustrating problem.

**My linux server:**
 - OS: [ubuntu]
 - Version [16.04]
 - gcc version:[5.4.0]

**Hope**
Can you give me some specific suggestions?Because my PC doesn't have GPUs,so i have to use the server in my college's lab,this really 
a big problem for me   >_<

**Comment by asselkembay** [comment]
> **A problem about Installing the norse** when i used conda to install norse(v.0.0.7) in a linux server(ubuntu16.04),which can successfully be installed,but when i import norse in python,it said: _ModuleNotFoundError:No module named 'norse'_ .Then i choose to use command ’pip install norse==0.0.7',then an error was showed: _ERROR: Could not build wheels for norse which use PEP 517 and cannot be installed directly_
> 
> **Methods been tried**
> 
> 1. `conda install -c norse norse==0.0.7`  this command can successfully install norse, but can't import module.
> 2. `pip install norse `    this command will erupt many red mistakes,i have already uninstalled norse before using this command
> 3. i guessed that maybe there were some packages conflicts,so i try to create a new virtual environment using `conda create  -n  pytorch_snn  python=3.9`,then install all dependencies required , but it still didn't work
> 
> **Screenshots** ![错误2](https://user-images.githubusercontent.com/79414489/147450167-6f053de5-f7ee-4a1b-85ce-72cd4051008b.png) ![错误](https://user-images.githubusercontent.com/79414489/147450141-2b86b8a6-fb6b-4738-8563-715b1b53cfec.png)
> 
> ### i had asked for help on the internet,but nobody could solve this problem.It is really a frustrating problem.
> **My linux server:**
> 
> * OS: [ubuntu]
> * Version [16.04]
> * gcc version:[5.4.0]
> 
> **Hope** Can you give me some specific suggestions?Because my PC doesn't have GPUs,so i have to use the server in my college's lab,this really a big problem for me >_<

Hi! I might be wrong, but I experienced a similar issue a few months ago. I think you need a newer version of gcc. Could you please upgrade your gcc version and try it again? Because after upgrading gcc, my problem was resolved. I'm hoping it'll help you fix your problem. Best of luck!

**Comment by Jegp** [comment]
Hey! Sorry to hear about your frustration, but I'm grateful you're reporting the problem so we can solve it for future reference. I have two pointers

1. The screenshot you provided seemed to show that Norse wasn't installed correctly. Could you try to install the buildtool Ninja and try again (`pip install ninja`)?
2. When you installed via Conda and it successfully installed, could you verify that Norse is shown when you type `conda list`? If the package is listed, then it *should* be installed.

**Comment by codefwer** [comment]
> Hey! Sorry to hear about your frustration, but I'm grateful you're reporting the problem so we can solve it for future reference. I have two pointers
> 
> 1. The screenshot you provided seemed to show that Norse wasn't installed correctly. Could you try to install the buildtool Ninja and try again (`pip install ninja`)?
> 2. When you installed via Conda and it successfully installed, could you verify that Norse is shown when you type `conda list`? If the package is listed, then it _should_ be installed.

I am so happy that you can give me some suggestions,i installed  ninja using pip again,but when i  use `conda list` ,the norse is really listed,then when i import it in python ,just like the screenshot showed:
![错误3](https://user-images.githubusercontent.com/79414489/147566218-37f809e7-f0e0-4f9a-a73f-f752a45c1759.png)

**Comment by Jegp** [comment]
I'm unfortunately not an export in Conda, but could you verify that you're in the right environment? This thread may be helpful: https://askubuntu.com/a/1180824

A manual way of doing it is to check the value of your `PYTHONPATH` environment variable (try the command `env`). That should tell you all the paths that Python is trying to look for libraries. You can manually add the path to wherever Norse is installed by resetting your variable (shown here: https://askubuntu.com/a/250935).

Let me know if this helps!

**Comment by codefwer** [comment]
> > **A problem about Installing the norse** when i used conda to install norse(v.0.0.7) in a linux server(ubuntu16.04),which can successfully be installed,but when i import norse in python,it said: _ModuleNotFoundError:No module named 'norse'_ .Then i choose to use command ’pip install norse==0.0.7',then an error was showed: _ERROR: Could not build wheels for norse which use PEP 517 and cannot be installed directly_
> > **Methods been tried**
> > 
> > 1. `conda install -c norse norse==0.0.7`  this command can successfully install norse, but can't import module.
> > 2. `pip install norse `    this command will erupt many red mistakes,i have already uninstalled norse before using this command
> > 3. i guessed that maybe there were some packages conflicts,so i try to create a new virtual environment using `conda create  -n  pytorch_snn  python=3.9`,then install all dependencies required , but it still didn't work
> > 
> > **Screenshots** ![错误2](https://user-images.githubusercontent.com/79414489/147450167-6f053de5-f7ee-4a1b-85ce-72cd4051008b.png) ![错误](https://user-images.githubusercontent.com/79414489/147450141-2b86b8a6-fb6b-4738-8563-715b1b53cfec.png)
> > ### i had asked for help on the internet,but nobody could solve this problem.It is really a frustrating problem.
> > **My linux server:**
> > 
> > * OS: [ubuntu]
> > * Version [16.04]
> > * gcc version:[5.4.0]
> > 
> > **Hope** Can you give me some specific suggestions?Because my PC doesn't have GPUs,so i have to use the server in my college's lab,this really a big problem for me >_<
> 
> Hi! I might be wrong, but I experienced a similar issue a few months ago. I think you need a newer version of gcc. Could you please upgrade your gcc version and try it again? Because after upgrading gcc, my problem was resolved. I'm hoping it'll help you fix your problem. Best of luck!

Thanks my brother,you are right ,after i upgrade my gcc and g++ compiler to version 7.5.0 in conda's virtual environment ,i can install norse and also import it in python

**Comment by codefwer** [comment]
> 

I am so sorry to reply  you so late,i solve this problem by upgrading my gcc and g++compiler to version 7.5.0, after install norse by following method i can import it in python.
 **method**
1.` conda install -c conda-forge gxx_linux-64==7.5.0 ` this step is downloading the g++ and gcc compiler (version 7.5.0,you can choose other versions you want) from conda-forege channel
2.`ln -s  /home/user_name/anaconda3/envs/your_env_name/libexec/gcc/x86_64-conda-linux-gnu/7.5.0/gcc  /home/user_name/anaconda3/envs/your_env_name/bin/gcc`  this step is building soft links,
3.`gcc -v` you will find your gcc compiler in current virtual environment has been upgraded to version 7.5.0
4. `cd  ~/norse-master`norse-master is the dir  where norse's source code downloading from github is stored,then input `python setup.py install`,norse will be installed
**screenshot**
![错误解决](https://user-images.githubusercontent.com/79414489/147847854-f230e88e-d2d3-4660-9e3e-0a1ecaa1de36.png)

**Comment by Jegp** [comment]
Happy to hear it worked! I'll close the issue for now. Please don't hesitate to re-open or ping us again! :)
