### ISSUE TITLE
Potential error in LIF adjoint

### ISSUE THREAD

**Issue by AaronSpieler** [norse/norse#287]
Hello,

I was just looking through the code and stumbled across these lines:

https://github.com/norse/norse/blob/04312dc95da657b82e43430c6e390b9414213ba6/norse/torch/functional/adjoint/lif_adjoint.py#L39-L42

I believe there could be an error in line 40, as this computation would yield the same result for 'dv_m' and 'dv_p'.

The same issue might occur at these lines:

https://github.com/norse/norse/blob/04312dc95da657b82e43430c6e390b9414213ba6/norse/torch/functional/adjoint/lif_adjoint.py#L136-L139

Best,
Aaron

**Comment by cpehle** [comment]
This is indeed a bug, I think it crept in, when I refactored the code to use the "state" named tuple.
