### ISSUE TITLE
Latex equation in documentation not rendered

### ISSUE THREAD

**Issue by manuelbre** [norse/norse#294]
**Describe the bug**
Some of the latex equation in the docstrings seem to be broken they are not rendered correctly in the online documentation

**Screenshots**
I found the following broken equations:
- Equation is not rendered at https://norse.github.io/norse/generated/norse.torch.module.lsnn.LSNNRecurrentCell.html#lsnnrecurrentcell
![image](https://user-images.githubusercontent.com/32066193/153224469-ae2f821a-779b-4a8a-bda6-11e3d394253f.png)

- Equation for the current does not start at new line at https://norse.github.io/norse/generated/norse.torch.LIFRecurrentCell.html#lifrecurrentcell
![image](https://user-images.githubusercontent.com/32066193/153224710-c44729c7-7285-447a-b2af-af4f8a876259.png)

**Comment by Jegp** [comment]
Thanks for the catch!
