### ISSUE TITLE
Jupyter Notebook Tutorials use a transformation on MNIST that does not convert it to [0,1] range thus producing incoherences when using Poisson Encoding

### ISSUE THREAD

**Issue by aitor-martinez-seras** [norse/norse#295]
**Problem**
The MNIST dataset is transformed using ``torchvision.transforms.Normalize((0.1307,), (0.3081,))`` , thus producing images ranging [-0.4242, 2.8215]. In the other hand, Poisson enconder, as Norse's documentation explicits, expects the input to be in the range of [0,1] in the case of [norse.torch.functional.poisson_encode](https://norse.github.io/norse/generated/norse.torch.functional.poisson_encode.html#norse.torch.functional.poisson_encode) and in the range of [-1,1] in the case of [norse.torch.functional.signed_poisson_encode](https://norse.github.io/norse/generated/norse.torch.functional.signed_poisson_encode.html#norse.torch.functional.signed_poisson_encode). Hence, as poisson_encode is used, pixels outside the range of [0,1] are capped to the min and max value respectively, resulting in a loss of information. 

**Solution**
The simple solution will be just to not use the mentioned transformation as torchvision ranges MNIST automatically to [0,1].

**Alternative**
Other more likely but also more complex solution will be to add a functionality to poisson_enconder to define the range of the input data.

**Comment by aitor-martinez-seras** [comment]
After running more test, I've realised that the loss of information only happens for values below the 0. The explanation is that if the input pixel values exceed the max value of the range [0,1] the resulting spikes are drawn from a Poisson distribution with a mu value (the mean of the Poisson distribution) linearly proportional to the mu value when the input value is 1 (the maximum). That is, the f_max parameter is defining the frecuency when the input value is 1, acting as a reference, but not limiting the value of the frecuency.

In contrast,  when the input value is below 0, as the 0 defines the case where the probability of generating a spike in a specific timestep is 0 and negative probailities are not possible, the input values below 0 just dont generate any spike, resulting in a loss of information.

**Comment by Jegp** [comment]
Great catch! Thanks a lot for pointing this out.

I'm slightly strung up on work currently, but I'll try to get it settled in the next couple of days. I'm in the process of giving the notebooks an overhaul in relation to a workshop anyway, so I may get around to it this week.

Please also note that we're more than happy to accept contributions :)

**Comment by Jegp** [comment]
I'll close the issue here so we can continue discussing it in https://github.com/norse/notebooks/pull/22
