### ISSUE TITLE
Factor out (parts of) the documentation

### ISSUE THREAD

**Issue by cpehle** [norse/norse#3]
Right now the generated sphinx documentation is committed to the main repository (mainly so that github.io was easy to setup). It would probably be a good idea to move this either to a separate repository or generate documentation through GitHub actions. I've also slightly modified the alabaster theme, so that modification would need to be hosted aswell.

**Comment by Jegp** [comment]
Could this be a part of the actions? Such that the action pipeline generates the docs and serves them?

**Comment by cpehle** [comment]
I've now deleted the autogenerated documentation and opted for manually hosting the documentation at [norse.ai/docs](norse.ai/docs). This is not ideal, but at least does not pollute the commit history with noise.
