### ISSUE TITLE
Time Constants Implementation

### ISSUE THREAD

**Issue by AaronSpieler** [norse/norse#302]
Hello,

I was wondering about your implementation of LIF and its time constants:

https://github.com/norse/norse/blob/3d425a959f2484ed447bc992c23e14b896d17aa7/norse/torch/functional/lif.py#L145-L147

You basically calculate a decay for `tau=20` and `dt = 1` of `1-1/20=0.95`, however, it should be `exp(-1/20)=0.9512`...
This difference is especially stark for small `tau=01`: `1-1/1=0` vs  `exp(-1/1)=0.3678`.

Am I missing something?

Best,
Aaron

**Comment by Jegp** [comment]
We're implementing the neuron dynamics as differential equations. You're correct that, according to [Gerstner et al.](https://neuronaldynamics.epfl.ch/index.html) the membrane `u`at a specific time `t` resolves to 

<img src="https://render.githubusercontent.com/render/math?math=u(t) = u_{leak} %2B RI_0 (1 - exp({-t}\over{\tau}))">

However, if you write this out as a dynamical system, where `u` evolves according to some time `t`, then the equation looks as follows (see equation 1.5 in the above reference):

<img src="https://render.githubusercontent.com/render/math?math={du}\over{dt}= \tau^{-1} \left(u_{leak} - u(t) %2B RI(t)\right)">

Which should be pretty much what you see in the equation above, if you set R = 1.

Did that help address the question? The specific values of the time constants will naturally depend on the situation. The current values are likely suboptimal.

**Comment by cpehle** [comment]
We are using naive Euler integration here, which has precision problems if the timestep dt and time constants are chosen outside of sensible ranges. One way to address this is to use exponential Euler integration as you are (implicitly) suggesting in your question. I'm actively considering to implement a more general solver infrastructure, one reason why this is taking some time is that I ideally also want to support the work I did on EventProp with Timo Wunderlich at the same time. You are welcome to suggest improvements as well, though. If this is a limiting factor for you it would be relatively easy to implement the exact exponential Euler Integration for LIF neurons.

**Comment by AaronSpieler** [comment]
Ahhh yes, both of your answers make sense. Thanks for your quick answers! I think the precision should be fine.
I was just confused when comparing two implementations, but I needed to know exactly how to intervene in the equation.

Best,
Aaron
