### ISSUE TITLE
Rename master -> main

### ISSUE THREAD

**Issue by cpehle** [norse/norse#315]
This is common practice now and should be the default anyways. We need to make sure that this doesn't introduce too many breaks, so we need to know which parts of the CI / doc flow explicitly refer to the 'master' branch.

**Comment by Jegp** [comment]
Good point! We should probably just walk through this list: https://github.com/norse/norse/search?q=master

**Comment by Jegp** [comment]
Thanks to GitHub, this was stunningly easy: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch
:tada:

**Comment by cpehle** [comment]
Nice
