### ISSUE TITLE
Regularisation

### ISSUE THREAD

**Issue by cpehle** [norse/norse#32]
There are a number of spike based regularisation schemes that we should implement. In this issue we can track the state of the art regarding regularisation in spiking neural networks.

- https://arxiv.org/pdf/1910.07407.pdf (upper and lower mean spike rate regularisation)

**Comment by Jegp** [comment]
From conversation w. @cpehle, one idea could be to do something along the lines of:
```
class RegularisationCell(torch.nn.Module):

  def forward(self, z : torch.Tensor, s : RegularisationState):
      return z, RegularisationState(s.num_spikes + torch.sum(z))
```
