### ISSUE TITLE
Task 'memory.py' is broken

### ISSUE THREAD

**Issue by ahenkes1** [norse/norse#340]
I tried to execute `norse/task/memory.py` by using `python3 -m norse.task.memory` as suggested (after cloning the repo and installing all libs via pip). This results in the following error:

> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/ah/norse/norse/task/memory.py", line 427, in <module>
>     main(args)
>   File "/home/ah/norse/norse/task/memory.py", line 293, in main
>     model = MemoryNet(input_features, output_features, args)
>   File "/home/ah/norse/norse/task/memory.py", line 58, in __init__
>     self.log("Neuron model", args.neuron_model)
>   File "/home/ah/.local/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 368, in log
>     apply_to_collection(
>   File "/home/ah/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 99, in apply_to_collection
>     return function(data, *args, **kwargs)
>   File "/home/ah/.local/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 533, in __check_allowed
>     raise ValueError(f"'self.log({name}, {value})' was called, but '{type(v).__name__}' values cannot be logged")
> ValueError: 'self.log(Neuron model, lsnnlif)' was called, but 'str' values cannot be logged
> 

I am able to execute other tasks using pytorch-lightning just fine, e.g., `python3 -m norse.task.mnist_pl` runs perfectly.
Is this a bug or am I missing something? The LSNN is an interesting topic and I want to explore this more in detail, it would be great to get some help!

I am using:
norse 0.0.7.post1
torch 1.12.0
pytorch-lightning 1.6.5

**Comment by Jegp** [comment]
Thanks for pointing this out! 

We're in the process of releasing a new version of this. I'll push the task as soon as I can.

**Comment by ahenkes1** [comment]
Thank you very much for the quick response, @Jegp !

**Comment by Jegp** [comment]
Alright, the PR should have fixed this. Could you kindly let me know if it's still not working? :-) Thanks for reporting!
