### ISSUE TITLE
Requirements incompatible with google collab

### ISSUE THREAD

**Issue by cpehle** [norse/norse#71]
The current requirements.txt specifies versions that are incompatible with google colab:
```
ERROR: google-colab 1.0.0 has requirement six~=1.12.0, but you'll have six 1.15.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
```
Since this is supposed to be one of the primary ways in which new users can try out the library, we should adjust the requirements accordingly.

**Comment by Jegp** [comment]
That is first of all quite weird, because we do not fix any dependencies for six, folium or imgaug. Could we also add a test for this, just to make sure we don't regress? That could be as simple as trying to install the above dependencies and verifying that the exit code is 0.

**Comment by cpehle** [comment]
I feel like the GitHub action that runs at every commit and uses requirements.txt covers at least part of that. We should notice if the unconstrained requirements lead to errors. The disadvantage of fixed versions is that it leads to conflicts with existing package installations, that don't actually reflect any real problem.

**Comment by Jegp** [comment]
Yeah, this is a hard nut to crack. I can see that the `pytorch` project uses fluid dependencies. Perhaps that + wheels is the way to go?
