### ISSUE TITLE
C++ version of neuron primitives

### ISSUE THREAD

**Issue by cpehle** [norse/norse#85]
Using the libtorch C++ extension api it is relatively straightforward to implement the core neuron primitives in C++. This would have the advantage of facilitating integration with alternative backends, such as neuromorphic hardware. This issue tracks progress towards this goal.

**Comment by Jegp** [comment]
Adding a benchmark before and after would also be interesting!

**Comment by cpehle** [comment]
See also #83.

**Comment by Jegp** [comment]
I'd like to close this issue, so we can move a step towards releasing 0.0.5. We will of course still work towards more optimized neuron primitives and neuromorphic backends. But native versions of superspike and LIF dynamics is a good start I think.
